version: '2'
services:
  redis:
    image: redis:alpine
    container_name: auth-redis
    ports:
      - "10379:6379"
    networks:
      wee-net:
        ipv4_address: 172.16.238.14

networks:
  wee-net:
    driver: bridge
