version: '2'
services:
  auth:
    build: .
    container_name: auth-node
    command: ["start-auth.sh"]
    ports:
      - "10300:3000"
    networks:
      wee-net:
        ipv4_address: 172.16.238.10
    volumes:
      - ../dist:/app

networks:
  wee-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1
